package com.horo.ssm.dao.mapping;

import com.horo.ssm.dao.pojo.TbOrderDetail;

public interface TbOrderDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_detail
     *
     * @mbggenerated
     */
    int insert(TbOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_detail
     *
     * @mbggenerated
     */
    int insertSelective(TbOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_detail
     *
     * @mbggenerated
     */
    TbOrderDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbOrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbOrderDetail record);
}