package com.horo.ssm.dao.pojo;

import java.util.Date;

public class TbOrderDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detail.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detail.goods_date
     *
     * @mbggenerated
     */
    private Date goodsDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detail.o_orderid
     *
     * @mbggenerated
     */
    private String oOrderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detail.goodsid
     *
     * @mbggenerated
     */
    private Integer goodsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detail.goodsname
     *
     * @mbggenerated
     */
    private String goodsname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detail.goodsprice
     *
     * @mbggenerated
     */
    private String goodsprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_detail.goods_description
     *
     * @mbggenerated
     */
    private String goodsDescription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detail.id
     *
     * @return the value of t_order_detail.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detail.id
     *
     * @param id the value for t_order_detail.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detail.goods_date
     *
     * @return the value of t_order_detail.goods_date
     *
     * @mbggenerated
     */
    public Date getGoodsDate() {
        return goodsDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detail.goods_date
     *
     * @param goodsDate the value for t_order_detail.goods_date
     *
     * @mbggenerated
     */
    public void setGoodsDate(Date goodsDate) {
        this.goodsDate = goodsDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detail.o_orderid
     *
     * @return the value of t_order_detail.o_orderid
     *
     * @mbggenerated
     */
    public String getoOrderid() {
        return oOrderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detail.o_orderid
     *
     * @param oOrderid the value for t_order_detail.o_orderid
     *
     * @mbggenerated
     */
    public void setoOrderid(String oOrderid) {
        this.oOrderid = oOrderid == null ? null : oOrderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detail.goodsid
     *
     * @return the value of t_order_detail.goodsid
     *
     * @mbggenerated
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detail.goodsid
     *
     * @param goodsid the value for t_order_detail.goodsid
     *
     * @mbggenerated
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detail.goodsname
     *
     * @return the value of t_order_detail.goodsname
     *
     * @mbggenerated
     */
    public String getGoodsname() {
        return goodsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detail.goodsname
     *
     * @param goodsname the value for t_order_detail.goodsname
     *
     * @mbggenerated
     */
    public void setGoodsname(String goodsname) {
        this.goodsname = goodsname == null ? null : goodsname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detail.goodsprice
     *
     * @return the value of t_order_detail.goodsprice
     *
     * @mbggenerated
     */
    public String getGoodsprice() {
        return goodsprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detail.goodsprice
     *
     * @param goodsprice the value for t_order_detail.goodsprice
     *
     * @mbggenerated
     */
    public void setGoodsprice(String goodsprice) {
        this.goodsprice = goodsprice == null ? null : goodsprice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_detail.goods_description
     *
     * @return the value of t_order_detail.goods_description
     *
     * @mbggenerated
     */
    public String getGoodsDescription() {
        return goodsDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_detail.goods_description
     *
     * @param goodsDescription the value for t_order_detail.goods_description
     *
     * @mbggenerated
     */
    public void setGoodsDescription(String goodsDescription) {
        this.goodsDescription = goodsDescription == null ? null : goodsDescription.trim();
    }
}